name: Build all

on:
  push:
    branches:
     - main
     - release/*
     - 2.5.0
     - 2.5.0-*
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - 'localization/**'
     - 'resources/**'
     - ".github/workflows/build_*.yml"
     - 'tests/**'

  pull_request:
    branches:
     - main
     - release/*
     - 2.5.0
    paths:
     - 'deps/**'
     - 'deps_src/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - ".github/workflows/build_*.yml"
     - 'build_linux.sh'
     - 'tests/**'

  workflow_dispatch:
    inputs:
      build-deps-only:
        description: 'Only build dependencies (bypasses caching)'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_linux:
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: ubuntu-24.04
      build-deps-only: ${{ inputs.build-deps-only || false }}
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    needs: build_linux
    if: ${{ !cancelled() && success() && !inputs.build-deps-only }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            scripts
            tests
      - name: Apt-Install Dependencies
        uses: ./.github/actions/apt-install-deps
      - name: Restore Test Artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ github.sha }}-tests
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~4.3.0"
          useLocalCache: true
          useCloudCache: true
      - name: Unpackage and Run Unit Tests
        timeout-minutes: 20
        run: |
          tar -xvf build_tests.tar
          scripts/run_unit_tests.sh
      - name: Upload Test Logs
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: unit-test-logs
          path: build/tests/**/*.log
      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "ctest_results.xml"
      - name: Delete Test Artifact
        if: success()
        uses: geekyeggo/delete-artifact@v6
        with:
          name: ${{ github.sha }}-tests
